import { validateOrReject } from 'class-validator';
import { BadRequestError } from '../errors/BadRequestError';
import { CreateUserValidationSchema } from '../modules/user/user.dto';
import { Request, Response, NextFunction, RequestHandler } from 'express';

export const createUserValidator: RequestHandler = async (
  req: Request,
  _res: Response,
  next: NextFunction,
) => {
  try {
    if (!req.body) {
      throw new BadRequestError('Missing request body');
    }

    const user = new CreateUserValidationSchema();
    user.name = req.body.name;
    user.email = req.body.email;
    user.password = req.body.password;

    await validateOrReject(user);
    next();
  } catch (error) {
    // handles the error generated by class-validator
    // const message = Object.values(e[0].constraints)[0];
    // res.status(400).send({ message });

    next(error);
  }
};
